version: '2'

networks:
  oni:
    driver: bridge
    ipam:
      config:
      - subnet: 172.10.0.0/16
        gateway: 172.10.5.254
        aux_addresses:
          symfony: 172.10.1.2
          mysql-server: 172.10.1.3
          redis-server: 172.10.1.4

services:
    symfony:
        build:
            context: .
        image: oni-system:latest
        container_name: "oni-system"
        ports:
            - "8080:80"
        networks:
            - oni
        environment:
            - SYMFONY_ENV=dev
            - SYMFONY_DIRECTORY=/var/www
            - SYMFONY_INIT_site1=True
            - SYMFONY_PREV_site1=./init.sh
        volumes:
            - ~/web/oniSystem:/var/www/oniSystem
            - ./composer:/var/www/.composer
        links:
            - mysql-server
    mysql-server:
        image: mysql
        container_name: "oni-mysql"
        ports:
            - 3307:3306
        volumes:
            - oni-mysql:/var/lib/mysql
        networks:
            - oni
        environment:
            - MYSQL_DATABASE=oni-system
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=oni
            - MYSQL_PASSWORD=password
    redis:
        image: redis
        ports:
            - 6378:6379
        networks:
            - oni

volumes:
  oni-mysql:
